
const storyTutorials = require("./api/story-tutorial/story-tutorial.js");
test('Get Story Tutorial by ID', async () => {
    let response = await storyTutorials.fetchMerchantStoryTutorialDetail(1);
    let data = response.data;
    expect(data).toHaveProperty('id');
    expect(data).toHaveProperty('name');
    expect(data).toHaveProperty('title.id');
    expect(data).toHaveProperty('title.en');
    expect(data).toHaveProperty('title.my');
    expect(data).toHaveProperty('description.id');
    expect(data).toHaveProperty('description.en');
    expect(data).toHaveProperty('description.my');
    expect(data).toHaveProperty('image.url');
    expect(data).toHaveProperty('options.id');
    expect(data).toHaveProperty('options.autoPlay');
    expect(data).toHaveProperty('options.autoPlaySpeed');
    expect(data).toHaveProperty('options.buttons[0].id');
    expect(data).toHaveProperty('options.buttons[0].type');
    expect(data).toHaveProperty('options.buttons[0].bgColor');
    expect(data).toHaveProperty('options.buttons[0].textColor');
    expect(data).toHaveProperty('options.buttons[0].en');
    expect(data).toHaveProperty('options.buttons[0].my');
    expect(data).toHaveProperty('options.buttons[0].zw');
    expect(data).toHaveProperty('options.buttons[0].deeplink.name');
    expect(data).toHaveProperty('options.buttons[0].deeplink.is_external');
    expect(data).toHaveProperty('options.buttons[0].deeplink.is_webURL');
    expect(data).toHaveProperty('options.buttons[0].deeplink.alternative_url');
    expect(data).toHaveProperty('options.buttons[0].deeplink.client_id');
    expect(data).toHaveProperty('stories[0].id');
    expect(data).toHaveProperty('stories[0].en.id');
    expect(data).toHaveProperty('stories[0].en.extra_large.url');
    expect(data).toHaveProperty('stories[0].en.large.url');
    expect(data).toHaveProperty('stories[0].en.mid.url');
    expect(data).toHaveProperty('stories[0].en.small.url');
    expect(data).toHaveProperty('stories[0].en.extra_small.url');
    expect(data).toHaveProperty('stories[0].id');
    expect(data).toHaveProperty('stories[0].my.id');
    expect(data).toHaveProperty('stories[0].my.extra_large.url');
    expect(data).toHaveProperty('stories[0].my.large.url');
    expect(data).toHaveProperty('stories[0].my.mid.url');
    expect(data).toHaveProperty('stories[0].my.small.url');
    expect(data).toHaveProperty('stories[0].my.extra_small.url');
});