version: '3'
services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_DB=strapi
      - POSTGRES_PASSWORD=strapi
    ports:
      - "5432:5432"
    volumes:
      - "./../postgres:/var/lib/postgresql/data"
